GET http://localhost:2022/test


###

POST http://localhost:2022/user/registration
Content-Type: application/json

{
  "email": "11@gmail.com",
  "password": "SECRETOS"
}

###

DELETE http://localhost:2022/user/delete/60f03c840866843c347570ce
Content-Type: application/json
authotization: eyJhbGciONiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhcm9uQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYwZjAzODFmOTc0Y2I3NDQ1OGQ2Njg3ZSIsImlhdCI6MTYyNjM1Njc3OSwiZXhwIjoxNjI2MzYwMzc5fQ.6Wz2gMwWpmz8VU_b-SJfEAmpMIekrLQadaPMnRlp7ow"

###

POST http://localhost:2022/user/login
Content-Type: application/json

{
  "email": "aaron@gmail.com",
  "password": "SECRETOS"
}


//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhcm9uQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYwZjAzODFmOTc0Y2I3NDQ1OGQ2Njg3ZSIsImlhdCI6MTYyNjM1NTk1NSwiZXhwIjoxNjI2MzU5NTU1fQ.BOiB5F9-DggP2zgvErFT_ymAwDRhT2raZcsHr6ybSr0


###

POST http://localhost:2022/posts/new
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhcm9uQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYwZjAzODFmOTc0Y2I3NDQ1OGQ2Njg3ZSIsImlhdCI6MTYyNjUzOTYzOCwiZXhwIjoxNjI2NTQzMjM4fQ.-CRtqaKw6LJnwrMELHIINvFNc4banJUN1rK4WkKukNY
Content-Type: application/json

{
  "title": "autorizado post",
  "content": "yasssss"
}